### ISSUE TITLE
ClassCastException of flutter_inappwebview library 

### ISSUE THREAD

**Issue by abed-supy-io** [Nika0000/cloudflare_turnstile#18]
**Describe the bug**
android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter

PlatformException(error, android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter, null, java.lang.ClassCastException: android.webkit.WebSettingsWrapper cannot be cast to com.android.webview.chromium.ContentSettingsAdapter
	at Ye0.convertSettings(chromium-TrichromeWebViewGoogle.apk-stable-443021036:2)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:423)
	at Zc.invoke(chromium-TrichromeWebViewGoogle.apk-stable-443021036:5)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1008)
	at $Proxy6.convertSettings(Unknown Source)
	at androidx.webkit.internal.WebkitToCompatConverter.convertSettings(WebkitToCompatConverter.java:60)
	at androidx.webkit.WebSettingsCompat.getAdapter(WebSettingsCompat.java:911)
	at androidx.webkit.WebSettingsCompat.setForceDarkStrategy(WebSettingsCompat.java:544)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:362)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7680)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:423)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	
This bug has reported to my sentry , i found the issue has been solved on flutter_inappwebview with beta version
we need to update it here once it's live
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2397

**Comment by Nika0000** [comment]
> @Nika0000 Please this is important it is stopping us from publishing Android with Turnstile. Apreciate it !

I will try my best to fix this issue today

**Comment by Nika0000** [comment]
Try [new version](https://pub.dev/packages/cloudflare_turnstile).
